add_newline = true

format = '''
[┌───────────────────>](bold green)
[│](bold green)$username@$hostname$directory$git_branch$git_commit$cmd_duration
[└─>](bold green) $status '''

 [line_break]
 disabled = true
 
 [cmd_duration]
 min_time = 500
 format = 'took [$duration](bold yellow)'
 
 [character] 
 success_symbol = "[➜](bold green) "
 error_symbol = "[✖](bold red)"
 
 [username]
 style_user = "underline yellow bold"
 style_root = "underline red bold"
 format = '[$user]($style)'
 disabled = false
 show_always = true
 
 [hostname]
 ssh_only = false
 format =  "[$hostname](bold fg:202) "
 disabled = false

 [status]
 format = "[$symbol]($style)"
 success_symbol = "[➜](bold green) "
 disabled = false

 [directory]
 truncation_symbol = '…/'

 [git_commit]
 commit_hash_length = 4
 tag_symbol = '🔖 '
 only_detached = false
